/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.clase6;

import javax.swing.JOptionPane;

/**
 *
 * @author freddymonterroso
 */
public class Listados extends javax.swing.JFrame {

    /**
     * Creates new form Listados
     */
    
    
    public Listados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        mayus = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        num = new javax.swing.JLabel();
        car = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Verificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mayus.setForeground(new java.awt.Color(255, 0, 51));
        mayus.setText("jLabel1");

        min.setForeground(new java.awt.Color(255, 0, 51));
        min.setText("jLabel1");

        num.setForeground(new java.awt.Color(255, 0, 51));
        num.setText("jLabel1");

        car.setForeground(new java.awt.Color(255, 0, 51));
        car.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mayus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1))
                    .addComponent(min, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(car, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(mayus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(min)
                .addGap(18, 18, 18)
                .addComponent(num)
                .addGap(18, 18, 18)
                .addComponent(car)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String passwords = password.getText();
        
        // Una letra mayuscula
        // Una letra minuscula
        // Un caracter especial
        // Un numbero
        
        boolean mayuscula = false;
        boolean minuscula = false;
        boolean numeros = false;
        boolean caracter = false;
        
        for (int i = 0; i < passwords.length(); i++) {
            System.out.println(""+ passwords.charAt(i));
            
            if (Character.isUpperCase(passwords.charAt(i))) {
                mayuscula = true;
                System.out.println("Si tiene una mayuscula");
            } else if (Character.isLowerCase(passwords.charAt(i))) {
                minuscula = true;
                System.out.println("Si tiene una minuscula");
            }
            
            else if (Character.isDigit(passwords.charAt(i))) {
                numeros = true;
                System.out.println("Si tiene un numero");
            }
            
            else if (!Character.isLetterOrDigit(passwords.charAt(i))) {
                caracter = true;
                System.out.println("Tiene un caracter especial");
            }
        }
        
        if (!mayuscula) {
            mayus.setText("Le falta agregar una letra mayuscula");
            //JOptionPane.showMessageDialog(rootPane, "Le falta agregar una letra mayuscula");
        } 
        
        if (!minuscula) {
            min.setText("Le falta agregar una letra minuscula");
            //JOptionPane.showMessageDialog(rootPane, "Le falta agregar una letra minuscula");
        }
        
        if (!numeros) {
            num.setText("Le falta agregar una numero");
            //JOptionPane.showMessageDialog(rootPane, "Le falta agregar un numero");
        }
        
        if (!caracter) {
            car.setText("Le falta agregar un especial");
            //JOptionPane.showMessageDialog(rootPane, "Le falta agregar un caracter especial");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel car;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mayus;
    private javax.swing.JLabel min;
    private javax.swing.JLabel num;
    private javax.swing.JTextField password;
    // End of variables declaration//GEN-END:variables
}
